name: YouTube Downloader

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install yt-dlp & ffmpeg
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      - name: Download Audio via TV Client
        run: |
          yt-dlp \
            --extractor-args "youtube:player_client=tv,tv_embedded,ios" \
            -f "ba/b" \
            -x --audio-format mp3 \
            "https://www.youtube.com/watch?v=DM8FPq7gs6U"

      - name: Upload Downloaded File as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-audio
          path: "*.mp3"
