- name: Create Cookies File
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Download Audio
        run: |
          yt-dlp \
            --cookies cookies.txt \
            --extractor-args "youtube:player_client=android,web" \
            --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -f "ba/b" \
            -x --audio-format mp3 \
            "https://www.youtube.com/watch?v=DM8FPq7gs6U"
